include/xhyve/support/uuid.h

Fixes:
In file included from src/smbiostbl.c:37:
include/xhyve/support/uuid.h:81:53: error: cast from 'unsigned char const (*)[16]' to 'void *' drops const qualifier [-Werror,-Wcast-qual]
uuid_internal_t *u = (uuid_internal_t *) ((void *) uuid);
^
1 error generated.
make: *** [build/smbiostbl.o] Error 1

Fix compilation error under Xcode 7 (clang-700.0.53)

---

src/pci_ahci.c
src/pci_virtio_block.c

Adopt src/pci_ahci.c logic
struct ahci_port {
...
char ident[20 + 1];
...
}
as they both hold the MD5 sum. Also while at it start using snprintf.
Signed-off-by: S.Çağlar Onur <caglar@10ur.org>

vbsc_ident buffer accessed out of bounds

---

README.md

"GitHub Flavored Markdown" doesn't seem to work for markdown files in repo.
Cf.) markdown - github Readme - reference issue - Stack Overflow
http://stackoverflow.com/questions/16539687/github-readme-reference-issue

Fix issues' links in README

---

src/pci_hostbridge.c

I got a warning message as below. And I found it has been patched on upstream.
```
pci 0000:00:00.0: ignoring class 0x060000 (doesn't match header type 01)
```
Cf.)
- https://github.com/freebsd/freebsd/commit/ab4eab33be088c74ec511e42660e0a55e6334a5f
- http://lists.freebsd.org/pipermail/freebsd-virtualization/2015-June/003643.html
- http://lists.freebsd.org/pipermail/freebsd-virtualization/2015-June/003645.html

Fix a warning message about pci host bridge

---

include/xhyve/xhyve.h
src/pci_virtio_net_vmnet.c
src/xhyve.c

As the name suggests, this adds the -M command line flag that will tell Xhyve to print the MAC address and exit if using vmnet.
This only really has practical use if the -U flag is also supplied with a UUID, so that you can determine which MAC address the UUID will map to. This will allow you to determine the IP address of the guest by inspecting the DHCP leases on the host. The idea being you run xhyve first with the -M flag to figure out ahead of time the MAC and IP address it will get, and then run it for real without the -M flag.
A similar pattern is used by [docker-machine-xhyve](https://github.com/zchee/docker-machine-driver-xhyve/tree/master/vmnet), and the nearly identical [xhyve-ruby native extension](https://github.com/dalehamel/xhyve-ruby/blob/master/ext/vmnet/vmnet.c) that …

Add option to print MAC address and exit

---

src/acpi.c

Back ports recent change from bhyve.

Use strlcpy() instead of strncpy() because subsequent mkstemps expects the string be nul-terminated.

---

README.md

VirtualBox 4.3.30 also does not causes Kernel Panic and works good together
with xhyve. Tested on my machine.
See changelogs here:
https://www.virtualbox.org/wiki/Changelog-4.3

also add VirtualBox 4.3.30 to README

---

src/vmm/io/vhpet.c

OS X 10.11.4 (15E65)
Xcode Version 7.3 (7D175)
Apple LLVM version 7.3.0 (clang-703.0.29)

Fixing compilation on OS X 10.11.4 and Xcode 7.3

---

README.md

Just for the sake of completeness. People who care about remaining in user space even for virtualization, overlap a lot with people who install everything with `brew` to avoid any `sudo` , I imagine.

Added instructions for homebrew

---

include/xhyve/uart_emul.h
src/pci_lpc.c
src/pci_uart.c
src/uart_emul.c
src/xhyve.c

Enables to easily access xhyve guests through serial terminals. Demo: https://cldup.com/enMVXo6vKA.gif
For those unfamiliar with ptmx, there is a great explanation at http://unix.stackexchange.com/a/120018/128551

Adds option to create master/slave pseudo-terminals when adding LPC devices.

---

src/pci_virtio_net_vmnet.c

Recently bug #60 was closed and it was determined that OS X's existing permissions structure can't support granting special privileges to xhyve. It looks like the best way to set up networking for a vm without sudo is to use the setuid bit. However, after networking has been set up, root permissions are no longer needed and can be dropped. This PR drops privileges after networking has been initialized. As a bonus, it redirects the vmnet failure message to stderr instead of stdout.

Drop privileges

---

include/xhyve/lock.h
include/xhyve/vmm/io/vlapic_priv.h
src/vmm/io/vatpic.c
src/vmm/io/vatpit.c
src/vmm/io/vioapic.c
src/vmm/io/vlapic.c
src/vmm/vmm.c

- for 10.12, use os_unfair_lock from <os/lock.h> (as recommended by OSSpinLockDeprecated.h)
os_unfair_lock API reference: https://developer.apple.com/reference/os/os_unfair_lock
- refactor locking routines into a shared set of macros

OSSpinLock has been deprecated on 10.12

---

README.md

It currently takes some digging to check your CPU compatibility.  A one liner makes it easy.  To determine if your cpu is compatible, run `sysctl kern.hv_support` at the command line.  If the result is 1, you are xhyve ready.

Document how to determine a compatible CPU

---

src/vmm/vmm_api.c

This is related to FreeBSD-SA-16:38.bhyve[0] AKA CVE-2016-1889 which was
discovered by Felix Wilhelm. In the context of hyperkit the code in
question runs as an unprivileged user.
Thanks to Gleb Smirnoff and the FreeBSD security team for advanced
notice on this issue.
[0] https://lists.freebsd.org/pipermail/freebsd-announce/2016-December/001773.html

Avoid integer overflow in xh_vm_map_gpa()

---

include/xhyve/firmware/kexec.h
src/firmware/kexec.c

Fix `ramdisk_start` promlem in the `kexec.c`.
This pull request is backported to https://github.com/docker/hyperkit/pull/66.
As in the  https://github.com/mist64/xhyve/issues/116 and https://github.com/mist64/xhyve/issues/74, 
``` c
ramdisk_start = ALIGNUP((kernel.base + kernel.size), 0x1000ull);
```
That logic is sometimes `initrd` will overlap with the `kernel` memory space.
So, change calculation method using the `initrd_addr_max` variable from the kernel header data.
- Use the initrd_addr_max value from the kernel header if the kernel version is 2.03 or newer.
- ref: https://github.com/zchee/linux-documentation/blob/master/x86/boot.md#initrd_addr_max
- Use hardcoded(`0x37ffffff`) value if older.
- Compare the `initrd_max` and `lowmem.size`, and re-assign if `initrd_max` is larger.
- …

kexec: fix wrong calculation method of ramdisk_start

---

src/pci_ahci.c
src/pci_virtio_block.c
src/pci_virtio_net_tap.c
src/smbiostbl.c

Fix MacOSX 10.15 CC_MD5 deprecation errors

---

include/xhyve/vmm/intel/vmx.h
include/xhyve/vmm/intel/vmx_msr.h
src/vmm/intel/vmx.c
src/vmm/intel/vmx_msr.c
xhyve.xcodeproj/project.pbxproj

The previous code cared about Don't Care bits in capability fields for controls by terminating with an error when encountering any unknown ones. This causes problems on newer CPUs, which add new such bits for new features. It is safe and recommended to simply retain the current value in the respective control for such bits, and this change does that. Some rearchitecting was needed, because the previous code treated the capabilities as global.

don't care about "Don't Care" bits

---

src/xhyve-entitlements.plist

`com.apple.security.hypervisor` is a new entitlement to replace `com.apple.vm.hypervisor`. Keeping both so that it remains compatible with macOS 10.15 or earlier.
See: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_hypervisor

Add com.apple.security.hypervisor to entitlements

---

src/smbiostbl.c

Fixes #196  
According to the SMBIOS specification (revision 2.7 or newer), the
extended module size field should only be used for sizes that can't
fit in the older size field.
Based on: freebsd/freebsd@dd589c9906a9b7819a21ffb6d7a00a090be32f55

SMBIOS: Fix Type 17 table generation

---

src/vmm/intel/vmx.c

After using @shanesmith's patch I'm getting `hv_vm_create failed` on Big Sur. This PR would improve the visibility when we have issue with `hv_vm_create`. 
This patch is originally at https://github.com/moby/hyperkit/pull/223. Credit goes to @djs55.

Log the error if hv_vm_create fails

---

src/vmm/vmm_instruction_emul.c

This adds emulation for:
test r/m16, imm16
test r/m32, imm32
test r/m64, imm32 sign-extended to 64
OpenBSD guests compiled with clang 8.0.0 use TEST directly against a
Local APIC register instead of separate read via MOV followed by a
TEST against the register.
(Without this fix, OpenBSD 6.6+ guests with multiple CPUs will crash
xhvye with a "Failed to emulate instruction" error.)
Taken from https://github.com/freebsd/freebsd-src/commit/e4da41f932a5415ec01d08e97ff2cde948afa073
with explicit casts added to make the compiler happy.  Original upstream
(FreeBSD/bhyve) bug report:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238794

Emulate TEST r/m{16,32,64}, imm{16,32,32} instructions (fix OpenBSD SMP)

---

src/pci_ahci.c
src/vmm/vmm_instruction_emul.c

Apple clang-1300.0.29.3 (ships with macOS 11.6) requires to use `-Wno-shorten-64-to-32` and `-Wsnoign-conversion`, or explicitly cast to smaller type or signed type.
`immediate` is `int64_t` and `opsize` is 4 bits field which makes mask clearly no more than 5 bits => cast to `uint8_t` is safe here and just makes clang happy and code clean.
`buf[]` is also `uint8_t` and cast happened before but implicitly.

Explicitly cast to uint8_t

---

src/pci_e82545.c

Old clang fails such us shipped with Yosemite because it has no idea about `-Walloca`.

Added `-Wunknown-pragmas` as ignored pragma

---

include/xhyve/vmm/vmm_callout.h
src/vmm/io/vatpit.c
src/vmm/io/vhpet.c
src/vmm/vmm_callout.c

Tries to be a cleaner implementation then the current one, based upon what I saw in README.md - TODO I thought it was a good idea to migrate it. I wouldn't say it is complete, but it could be a good starting point. I haven't seen any issues by running a VM for a couple of hours with multiple sleeps with this patch.

Migrate vmm_callout -> OSX libdispatch
